# Example Github Actions workflow

name: Build and push Docker image

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      flutter_version:
        description: 'Image version'
        required: true
 
jobs:

  add-ip-whitelist:
    
    runs-on: ubuntu-latest
    steps:
    - name: Build Docker Image
      env:
       FLUTTER_VERSION: ${{ inputs.flutter_version }}
      run: |
        echo " myimage:$FLUTTER_VERSION"

  

