# Example Github Actions workflow

name: Build and push Docker image

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      flutter_version:
        description: 'Image version'
        required: true
        default: '2.5.3'
jobs:

  add-ip-whitelist:
    
    runs-on: ubuntu-latest
    steps:
    - name: Build Docker Image
      env:
       FLUTTER_VERSION: ${{ inputs.flutter_version }}
      run: |
       docker build \
       --build-arg FLUTTER_VERSION=${FLUTTER_VERSION} \
        -t myimage:$FLUTTER_VERSION .

  

