# Example Github Actions workflow

name: Build and push Docker image

on:
  
  workflow_dispatch:
    inputs:
      name:
        description: 'Image version [ default: latest]'
        required: true

 
jobs:

  build:
    
    runs-on: ubuntu-latest
    steps:
    - name: Docker images
      run : echo "hello:${{ github.event.inputs.name }}"

  

