name: Input Example

on:
  push:
    branches: [main]
    
  workflow_dispatch:
    inputs:
      username:
        description: "give me your username"
        default: "geralexgr"
        type: "string"


